name: Run LEAFlood
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        # Bookend python versions
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags.
      
      - name: Set up Python
        uses: actions/setup-python@v4
          with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgeos-dev
      - name: Upgrade pip and build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run LEAFlood
        run: |
          python LEAFlood.py
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Results for ${{ runner.os }}-${{ matrix.python-version }}
          path: output/*
